### ISSUE TITLE
How am I supposed to send you this ?

### ISSUE THREAD

**Issue by sametmax** [farjump/fwtr#3]
Congrats for making the front page of hacker news (https://news.ycombinator.com/item?id=11056766) :) 

I ran fwts and got a log:

http://0bin.net/paste/nP66r0TD-QTbanTg#4JRCDTyr2iXDucR8RsPxuZm8n-m1aSEFTq4AvPzxsim

Now, how am I suppose to identify which part is what log, separate them into separate files?

And should I make a PR to submit a report?

**Comment by Julio-Guerra** [comment]
@sametmax almost! I just added details on how to get the same kind of logs I obtained myself (https://github.com/farjump/fwtr#command-line). 

I can see you simply ran `fwts` which is fine (although I don't know what are the default test suites) but gives you a plain-text result file. Which is fine too but since we can get HTML too it is a shame not asking for them too with `--log-type html`.

Cf. https://github.com/farjump/fwtr#command-line

**Comment by sametmax** [comment]
Ok, done. I'm preparing a PR. How do I obtain the necessary informations to create the directory tree structure ? How do I know it's intel (intel what ?), nuc (what is nuc ?), etc.

**Comment by sametmax** [comment]
Ok, done. I'm preparing a PR. How do I obtain the necessary informations to create the directory tree structure ? How do I know it's intel (intel what ?), nuc (what is nuc ?), etc.

I read `<vendor>/<board-tree>/<firmware>/<version>/<testing-tool>/<test-variant>/<test-outputs>`. I just don't know how to find most of these informations, or even what they are, appart from testing-tool which I guess is fwts.

**Comment by Julio-Guerra** [comment]
You could try using a linux tool to get informations about your
motherboard? Or try entering your BIOS, it should say at least who is the
vendor. Maybe the motherboard's name will be displayed too.

The logs you posted say:
- BIOS Vendor : American Megatrends Inc
- BIOS Version : P05ACJ.128.140819.dg
- Board Name : NP940X3G-K03FR
- System vendor: Samsung

I let you confirm but we've got everything there. I googled a little bit to
understand what product you have and I understand you have a samsung laptop
whose motherboard is specifically constructed by AMI for Samsung. Every
name fwts got are samsung's, so I would go for something like
 `samsung/NP940X3G/fwts/<test>`. This is the kind of thing I would like to
know when buying this laptop: can I use it with my OS?

I would have done a symlink to this folder from `ami/NP940X3G/fwts/<test>`
I we could by the motherboard alone but it seems we can't so I would stop
there.

**Comment by JonasGroeger** [comment]
Try `sudo dmidecode -t bios`

**Comment by josteink** [comment]
@sametmax NUC is Intel's "Next Unit of Computing". Basically Intel's own attempt at [Mini PCs](http://www.intel.com/content/www/us/en/nuc/overview.html). They're very nice.

**Comment by sametmax** [comment]
Is  PR #7 ok ?

**Comment by Julio-Guerra** [comment]
Almost :) No worries, I'm on it. :+1:
