### ISSUE TITLE
Current DB is small

### ISSUE THREAD

**Issue by josteink** [farjump/fwtr#6]
This repo should be marketted or "spammed" in a friendly manner across social media to get more attention :)

**Comment by dbirks** [comment]
Nice idea. [This post](https://www.reddit.com/r/debian/comments/44vzgm/test_your_bios_and_share_your_results_on_github/) on /r/debian is what brought me here.

**Comment by Julio-Guerra** [comment]
I'm trying again: https://news.ycombinator.com/item?id=11117486 ^^ But it does not seem to be working this time.

**Comment by josteink** [comment]
I'm closing this issue for now. It seems we did get _some_ traffic after all :)
